### ISSUE TITLE
As a host I want to start a game and invite some members for the game in order to play together. 

### ISSUE THREAD

**Issue by homo-iocus** [sopra-fs23-group-18/pocket-party-server#1]
**Development Tasks:**

- [ ] sopra-fs23-group-18/pocket-party-web#4
- [ ] sopra-fs23-group-18/pocket-party-web#5
- [ ] sopra-fs23-group-18/pocket-party-web#3
- [ ] sopra-fs23-group-18/pocket-party-web#2
- [ ] sopra-fs23-group-18/pocket-party-web#6
- [ ] sopra-fs23-group-18/pocket-party-server#20
- [ ] sopra-fs23-group-18/pocket-party-server#21
- [ ] sopra-fs23-group-18/pocket-party-server#66
- [ ] #76
- [ ] #81
- [ ] #82

**Acceptance Criteria:**

- [ ] By clicking on a start button on the web app a host can start a new game, he gets redirected to a setup menu where he can choose the amount of players & the game mode like setting the specifications e.g amount of rounds to play
- [ ] After setting up the game, the hosts device gets redirected to the overview screen where a (QR) code for the players to join is displayed
- [ ] On the host device the players can be assigned to two teams which play against each other

**Priority: critical**
