### ISSUE TITLE
As a player I want to play 2vs2 pong against each other in order to get more score for the overall game.

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#10]
**Development Tasks**

- [x] sopra-fs23-group-18/pocket-party-web#63
- [x] sopra-fs23-group-18/pocket-party-web#65
- [x] sopra-fs23-group-18/pocket-party-web#66
- [x] sopra-fs23-group-18/pocket-party-web#67
- [x] sopra-fs23-group-18/pocket-party-mobile#25

**Acceptance Criteria:**

- [x] Basic pong where the players gets controlled by leaning the smartphone in the right direction.
- [x] When i lean the phone in one direction the game on the web-app should act on it.
- [x] On the Web-app the game get's displayed with 2 bars and a point moving around.

**Priority: medium**
