### ISSUE TITLE
Ideas/Issues from milestone 3 that will be worked on in milestones 4

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#100]
**Development Tasks:**

- [x] sopra-fs23-group-18/pocket-party-mobile#18
- [x] sopra-fs23-group-18/pocket-party-web#54
- [x] sopra-fs23-group-18/pocket-party-server#103
- [x] sopra-fs23-group-18/pocket-party-server#104
- [x] sopra-fs23-group-18/pocket-party-server#105
- [x] sopra-fs23-group-18/pocket-party-mobile#19
- [x] sopra-fs23-group-18/pocket-party-web#55
- [x] sopra-fs23-group-18/pocket-party-server#142
- [x] sopra-fs23-group-18/pocket-party-mobile#26
- [x] sopra-fs23-group-18/pocket-party-server#145
- [x] sopra-fs23-group-18/pocket-party-web#69
- [x] sopra-fs23-group-18/pocket-party-web#68
- [x] sopra-fs23-group-18/pocket-party-server#147
- [x] sopra-fs23-group-18/pocket-party-web#73
- [x] #155
