### ISSUE TITLE
As a user at the end of each minigame I want to see the current score for comparison with the other team.

### ISSUE THREAD

**Issue by homo-iocus** [sopra-fs23-group-18/pocket-party-server#12]
**Development Tasks:**
- [ ] sopra-fs23-group-18/pocket-party-server#70
- [ ] sopra-fs23-group-18/pocket-party-web#13
- [ ] sopra-fs23-group-18/pocket-party-web#14
- [ ] sopra-fs23-group-18/pocket-party-web#15
- [x] sopra-fs23-group-18/pocket-party-web#17
- [ ] sopra-fs23-group-18/pocket-party-server#71
- [ ] #83

**Acceptance Criteria:**

- [ ] At the end of each minigame the web app gets redirected to a score overview screen.
- [ ] In the overview screen first the score for the recently played game is shown.
- [ ] After some time the overall scores get displayed.
- [ ] After additional time the next minigame is announced.

**Priority: critical**
