### ISSUE TITLE
As players i want to see who has won on the host device.

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#13]
**Development Tasks:**

- [ ] sopra-fs23-group-18/pocket-party-server#61
- [ ] sopra-fs23-group-18/pocket-party-web#8
- [ ] sopra-fs23-group-18/pocket-party-web#9
- [ ] sopra-fs23-group-18/pocket-party-server#69
- [ ] sopra-fs23-group-18/pocket-party-web#10
- [ ] #79

**Acceptance Criteria:**
- [ ] After all rounds have been played a winning screen is displayed.
- [ ] After clicking a button the web app gets redirected to the initial overview screen.
**Priority: critical**
