### ISSUE TITLE
Additional tasks to do for last week

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#157]
**Development Tasks**

- [x] sopra-fs23-group-18/pocket-party-server#158
- [x] sopra-fs23-group-18/pocket-party-server#159
- [x] sopra-fs23-group-18/pocket-party-server#160
- [x] sopra-fs23-group-18/pocket-party-web#76
- [x] sopra-fs23-group-18/pocket-party-web#77
- [x] sopra-fs23-group-18/pocket-party-web#78
- [x] sopra-fs23-group-18/pocket-party-web#79
- [x] sopra-fs23-group-18/pocket-party-web#80
- [x] sopra-fs23-group-18/pocket-party-web#84
- [x] sopra-fs23-group-18/pocket-party-web#81
- [x] sopra-fs23-group-18/pocket-party-mobile#28
- [x] sopra-fs23-group-18/pocket-party-mobile#29
- [x] sopra-fs23-group-18/pocket-party-server#170
- [x] sopra-fs23-group-18/pocket-party-server#171
- [x] sopra-fs23-group-18/pocket-party-web#86

**Priority: high**
