### ISSUE TITLE
As a user I want to be able to scan a (QR) code for connecting my smartphone with the current game on the web app and choose a nickname.

### ISSUE THREAD

**Issue by homo-iocus** [sopra-fs23-group-18/pocket-party-server#2]
**Development Tasks**

- [x] sopra-fs23-group-18/pocket-party-mobile#3
- [ ] sopra-fs23-group-18/pocket-party-web#7
- [x] sopra-fs23-group-18/pocket-party-mobile#1
- [ ] sopra-fs23-group-18/pocket-party-mobile#2
- [ ] sopra-fs23-group-18/pocket-party-server#26
- [ ] sopra-fs23-group-18/pocket-party-web#12
- [ ] sopra-fs23-group-18/pocket-party-mobile#16

**Acceptance Criteria:**

- [ ] After scanning the code an input field for the nickname pops up. UI elements for choosing an avatar also gets shown
- [ ]  After choosing nickname and avatar a overview screen gets displayed, where all already joined players are visible 

**Priority: critical**
