### ISSUE TITLE
As a user I want to see a description of the mini game and who is playing before it starts in order to understand who's playing and what the minigame is about.

### ISSUE THREAD

**Issue by homo-iocus** [sopra-fs23-group-18/pocket-party-server#4]
**Development Tasks:**

- [ ] sopra-fs23-group-18/pocket-party-web#16
- [x] sopra-fs23-group-18/pocket-party-web#18
- [x] sopra-fs23-group-18/pocket-party-web#19
- [x] sopra-fs23-group-18/pocket-party-web#21
- [ ] sopra-fs23-group-18/pocket-party-server#32
- [ ] sopra-fs23-group-18/pocket-party-web#23
- [ ] sopra-fs23-group-18/pocket-party-server#34
- [ ] #80

**Acceptance Criteria:**

- [ ] At each round a minigame is drawn randomly by the web app, after a game has been choosen a description & preview of the game is shown on the host device.
- [ ] The amount of votes for each player are shown too. (Also see S4)

**Priority: critical**
