### ISSUE TITLE
As a player I want to play the game "Who can tap faster" in order to get more score for the overall game.

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#5]
**Development Tasks:**

- [ ] sopra-fs23-group-18/pocket-party-mobile#4
- [ ] sopra-fs23-group-18/pocket-party-mobile#5
- [ ] sopra-fs23-group-18/pocket-party-mobile#6
- [ ] sopra-fs23-group-18/pocket-party-web#27
- [ ] sopra-fs23-group-18/pocket-party-web#30
- [ ] sopra-fs23-group-18/pocket-party-server#40 
- [x] #84

**Acceptance Criteria:**

- [ ] The player with the most taps in a certain time period wins.
- [ ] Each time the player taps on his phone the counter on the web-app get's updated.
- [ ] After the game starts a counter of e.g 10 seconds starts.
- [ ] The current tap counter gets displayed and updated in real time on the host device.

**Priority: medium**
