### ISSUE TITLE
As a team member I want to vote for a player of my group to play the announced minigame in order to decide who's playing.

### ISSUE THREAD

**Issue by homo-iocus** [sopra-fs23-group-18/pocket-party-server#6]
**Development Tasks:**

- [ ] sopra-fs23-group-18/pocket-party-mobile#20
- [ ] sopra-fs23-group-18/pocket-party-mobile#21
- [ ] #135
- [ ] sopra-fs23-group-18/pocket-party-server#132
- [ ] sopra-fs23-group-18/pocket-party-server#133

**Acceptance Criteria:**

- [ ] On the mobile app each player gets a list of all the team members to vote for.
- [ ]  I can also vote for myself as player.
- [ ]  Depending on the amount of players needed for the minigame the voting screen adjusts. E.g. if two players are needed for the next game each team votes for 2 players instead of only one.
- [ ] After every one has voted the game starts automatically.

**Priority: low**
