### ISSUE TITLE
As a player I want to play the game vibration detection in order to get more score for the overall game.

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#7]
**Development Tasks**

- [x] sopra-fs23-group-18/pocket-party-mobile#22
- [x] sopra-fs23-group-18/pocket-party-web#58
- [x] sopra-fs23-group-18/pocket-party-web#59
- [x] sopra-fs23-group-18/pocket-party-mobile#23
- [x] sopra-fs23-group-18/pocket-party-web#61
- [x] sopra-fs23-group-18/pocket-party-web#60

**Acceptance Criteria:**

- [x] 3 Different patterns of vibrations get presented to the player. With a visual representation of the vibration on the host device.
- [x] After all patterns were shown to the players a single one of the vibration pattern gets replayed once.
- [x] The goal of the game is to choose the correct visual representation of the played vibration.
- [x] Input by clicking on a button on the smartphone.
- [x] Output via the smartphone vibrations api.

**Priority: medium**
