### ISSUE TITLE
As a player I want to play the game "TIMING GAME" in order to get more score for the overall game.

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#72]
**Development Tasks**

- [ ] sopra-fs23-group-18/pocket-party-web#24
- [ ] sopra-fs23-group-18/pocket-party-web#25
- [ ] sopra-fs23-group-18/pocket-party-web#26
- [ ] sopra-fs23-group-18/pocket-party-mobile#7
- [ ] sopra-fs23-group-18/pocket-party-web#28
- [ ] sopra-fs23-group-18/pocket-party-web#29
- [ ] sopra-fs23-group-18/pocket-party-web#33
- [x] #85

**Acceptance Criteria:**

- [ ] The principal is to catch falling objects by shaking the smartphone with the right timing.
- [ ] On the mobile you see an image of a phone being shaked and when you shake the phone your block moves on the web-app.
- [ ] On the web-app blocks are falling down from the top of the screen for each player and a timer is counting down.
- [ ] Depending on the accuracy of a hit the scores get's updated.

**Priority: critical**
