### ISSUE TITLE
As a host I want to get all my data back(game status etc.) if the web crashes for security.

### ISSUE THREAD

**Issue by SvenRingger** [sopra-fs23-group-18/pocket-party-server#77]
** Development Tasks:**

- [x] sopra-fs23-group-18/pocket-party-server#93
- [x] sopra-fs23-group-18/pocket-party-mobile#35
- [x] sopra-fs23-group-18/pocket-party-server#95

**Acceptance Criteria:**

- [x] I want to rejoin the lobby should I get kicked out as a player.
- [x] As a host I want to be able to close and open a lobby whenever I want to, while my data is being saved.
