### ISSUE TITLE
As a minigame player I want to establish and maintain a peer to peer connection with the web app using WebRTC inorder to have a low latency while playing the minigames.

### ISSUE THREAD

**Issue by homo-iocus** [sopra-fs23-group-18/pocket-party-server#9]
**Development Tasks:**
- [ ] sopra-fs23-group-18/pocket-party-server#41
- [ ] sopra-fs23-group-18/pocket-party-server#42
- [ ] sopra-fs23-group-18/pocket-party-server#43
- [ ] sopra-fs23-group-18/pocket-party-server#44
- [ ] sopra-fs23-group-18/pocket-party-web#31
- [ ] sopra-fs23-group-18/pocket-party-mobile#8
- [ ] sopra-fs23-group-18/pocket-party-web#34
- [ ] sopra-fs23-group-18/pocket-party-web#35
- [ ] sopra-fs23-group-18/pocket-party-web#36
- [ ] sopra-fs23-group-18/pocket-party-mobile#9
- [ ] sopra-fs23-group-18/pocket-party-mobile#10
- [ ] sopra-fs23-group-18/pocket-party-mobile#11

**Acceptance Criteria:**

- [ ] An WebRTC connection can be established & maintained by using the STUN & TURN approach.
- [ ] Depending on the input required for the minigame the host sends a message to the phone what type of data it needs and in which interval.
- [ ] The mobile app gets into play mode and sends the data in the form host and mobile client have aggreed on before hand.
- [ ] The web app updates it's view based on the input

**Priority: critical**
