### ISSUE TITLE
As a host i want to be able to change the settings for the game before it starts

### ISSUE THREAD

**Issue by Steesch** [sopra-fs23-group-18/pocket-party-server#96]
**Development Tasks:**

- [x] sopra-fs23-group-18/pocket-party-server#122
- [x] sopra-fs23-group-18/pocket-party-server#123
- [x] sopra-fs23-group-18/pocket-party-server#124
- [x] sopra-fs23-group-18/pocket-party-server#125
- [x] sopra-fs23-group-18/pocket-party-web#53
- [x] sopra-fs23-group-18/pocket-party-web#70
- [x] sopra-fs23-group-18/pocket-party-web#71
- [x] sopra-fs23-group-18/pocket-party-web#72

**Acceptance Criteria:**

- [x] The host can select several topics in the settings that get sent with the creation of the lobby.
- [x] The host can see these choices afterwards when playing the game.

**Priority: medium**
